In [3]:
list1 = list(range(10))

list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list2 = [2,3,6,7]
list2

[2, 3, 6, 7]

In [5]:
list12 = list1 + list2
list12

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 6, 7]

In [6]:
list21 = list2 + list1
list21

[2, 3, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
list3 = ["yes","No","Maybe"] * 3
list3

['yes', 'No', 'Maybe', 'yes', 'No', 'Maybe', 'yes', 'No', 'Maybe']

In [8]:
listtwo = f"{list1}{list1}"
listtwo

'[0, 1, 2, 3, 4, 5, 6, 7, 8, 9][0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'

In [9]:
list4 = ["2","3","9"]
list11 = [int(i) for i in list4]
list11 

[2, 3, 9]

In [10]:
list5 =[('abc','25'),('here','43'),('car','1')]
test = [i[0] for i in list5]
test

['abc', 'here', 'car']

In [11]:
from operator import itemgetter
list5.sort(key=itemgetter(1))
list5

[('car', '1'), ('abc', '25'), ('here', '43')]

In [12]:
from operator import itemgetter
list5.sort(key=itemgetter(0))
list5

[('abc', '25'), ('car', '1'), ('here', '43')]

In [13]:
import numpy as np

a = np.array([1,2,25,8])
b = np.array([1,5,6,90])

In [14]:
a * b 

array([  1,  10, 150, 720])

In [33]:
arr = a + b 

arr

array([ 2,  7, 31, 98])

In [16]:
arr2 = arr.tolist()

type(arr2)

list

In [17]:
arr3 = np.asarray(arr2)

arr3
type(arr3)

numpy.ndarray

In [18]:
np.column_stack((a))

array([[ 1,  2, 25,  8]])

In [19]:
np.row_stack((arr,arr))*4

array([[  8,  28, 124, 392],
       [  8,  28, 124, 392]])

In [20]:
np.column_stack((arr,a))

array([[ 2,  1],
       [ 7,  2],
       [31, 25],
       [98,  8]])

In [21]:
g =  [arr[0],arr[2]]
k = [arr[1],arr[3]]

In [30]:
f_array = np.column_stack((g,k))
f_array

array([[ 2,  7],
       [31, 98]])

In [23]:
g1 = np.asarray(g)
k1 = np.asarray(k)

In [24]:
np.column_stack((g1,k1))

array([[ 2,  7],
       [31, 98]])

In [26]:
 import scipy.stats as stats

In [32]:
# fishers test (odds ratio, p value)
oddsratio, pvalue = stats.fisher_exact(f_array)
pvalue

1.0

In [38]:
stats.fisher_exact([[2,7],[31,98]])

(0.9032258064516129, 1.0)

In [42]:
# chi squared (chi squared, p-value, degrees of freedom, expected array frequencies)
from scipy.stats import chi2_contingency
chi2_contingency(f_array)

(0.07903620926876745, 0.7786077832825409, 1, array([[ 2.15217391,  6.84782609],
        [30.84782609, 98.15217391]]))

In [49]:
chi2_contingency([[2,7,9],[20,70,0]])

(49.090909090909086,
 2.1879859813543596e-11,
 2,
 array([[ 3.66666667, 12.83333333,  1.5       ],
        [18.33333333, 64.16666667,  7.5       ]]))

In [65]:
import random
listOfNumbers1 = []
for x in range (0, 1000):
    listOfNumbers1.append(random.randint(-20, 50))
listOfNumbers1

[5,
 15,
 30,
 -15,
 23,
 -3,
 34,
 22,
 5,
 -10,
 37,
 14,
 25,
 29,
 26,
 20,
 31,
 -12,
 35,
 22,
 13,
 21,
 39,
 -4,
 43,
 47,
 -1,
 -20,
 3,
 37,
 12,
 3,
 39,
 24,
 -3,
 41,
 37,
 28,
 19,
 37,
 49,
 14,
 29,
 7,
 -16,
 40,
 14,
 -14,
 48,
 26,
 22,
 -1,
 26,
 43,
 -7,
 26,
 42,
 1,
 31,
 29,
 21,
 33,
 43,
 10,
 -7,
 -17,
 42,
 18,
 24,
 -8,
 37,
 31,
 16,
 6,
 25,
 -16,
 2,
 34,
 -14,
 35,
 32,
 -17,
 36,
 -3,
 14,
 -13,
 37,
 48,
 22,
 20,
 40,
 -20,
 5,
 -3,
 18,
 19,
 32,
 26,
 14,
 34,
 33,
 35,
 23,
 8,
 49,
 -19,
 45,
 -12,
 -15,
 43,
 28,
 42,
 -11,
 -3,
 19,
 40,
 48,
 -16,
 45,
 8,
 26,
 10,
 -18,
 16,
 -15,
 37,
 30,
 7,
 -4,
 15,
 41,
 30,
 49,
 32,
 41,
 46,
 15,
 -2,
 25,
 21,
 44,
 40,
 -17,
 14,
 -17,
 39,
 2,
 25,
 -14,
 26,
 29,
 -6,
 48,
 -12,
 32,
 6,
 19,
 27,
 4,
 2,
 18,
 2,
 -13,
 24,
 25,
 -12,
 41,
 42,
 17,
 11,
 -4,
 33,
 -7,
 38,
 22,
 -10,
 -2,
 26,
 -7,
 16,
 5,
 37,
 -3,
 35,
 39,
 -7,
 9,
 -11,
 23,
 -6,
 22,
 -20,
 14,
 21,
 -6,
 -14,
 46,
 14,


In [66]:
listOfNumbers2 = []
for x in range (0, 1000):
    listOfNumbers2.append(random.randint(-20, 50))
listOfNumbers2

[23,
 47,
 6,
 26,
 -13,
 -4,
 42,
 37,
 -1,
 0,
 2,
 7,
 5,
 26,
 50,
 26,
 8,
 44,
 30,
 -13,
 -1,
 -6,
 13,
 1,
 45,
 31,
 22,
 12,
 42,
 3,
 4,
 30,
 9,
 31,
 -16,
 0,
 -3,
 24,
 -19,
 31,
 10,
 25,
 40,
 36,
 14,
 18,
 30,
 21,
 42,
 0,
 26,
 31,
 7,
 48,
 14,
 30,
 -3,
 23,
 36,
 24,
 -19,
 23,
 46,
 25,
 -9,
 22,
 36,
 3,
 -3,
 8,
 28,
 -12,
 39,
 29,
 -10,
 27,
 47,
 24,
 -2,
 -15,
 -8,
 38,
 -3,
 33,
 30,
 25,
 -15,
 -10,
 -4,
 3,
 -20,
 -11,
 43,
 7,
 35,
 15,
 40,
 9,
 43,
 -20,
 16,
 -8,
 9,
 13,
 44,
 15,
 9,
 -18,
 39,
 27,
 6,
 13,
 11,
 44,
 -10,
 48,
 -7,
 -7,
 10,
 -5,
 7,
 30,
 -12,
 24,
 28,
 24,
 35,
 23,
 46,
 -7,
 -6,
 11,
 -9,
 20,
 39,
 -7,
 46,
 24,
 13,
 -9,
 -3,
 42,
 42,
 -2,
 47,
 45,
 12,
 33,
 -1,
 2,
 19,
 18,
 33,
 -19,
 9,
 21,
 48,
 31,
 44,
 14,
 44,
 30,
 7,
 10,
 10,
 22,
 -8,
 -10,
 13,
 40,
 -3,
 45,
 -12,
 27,
 41,
 33,
 -17,
 3,
 36,
 17,
 -16,
 41,
 9,
 34,
 9,
 35,
 6,
 14,
 37,
 -6,
 -15,
 29,
 27,
 29,
 -12,
 -4,
 47,
 -10,
 -15,
 41,
 4,


In [67]:
# Brunner Munzel non parametric, large sample size 
w, p_value = stats.brunnermunzel(listOfNumbers1,listOfNumbers2)
p_value

0.7589638845501381